### ISSUE TITLE
Can you share the core files ?

### ISSUE THREAD

**Issue by 827Dream** [wavestone-cdt/EDRSandblast#3]
Can you share all the core files involved in NtoskrnlOffsets.csv, if I want to find some offsets, I don’t have to search hard,thanks

**Comment by Qazeer** [comment]
Most of the `ntoskrnl.exe` files used to generate the offsets can be retrieved from [winbindex](https://winbindex.m417z.com) and [Microsoft public symbol servers](https://msdl.microsoft.com/download/symbols/)
using the provided `ExtractOffsets.py` script:

```
python ExtractOffsets.py -d -i <OUTPUT_FOLDER> -o doesnotmatter.csv ntoskrnl
```

**Comment by 827Dream** [comment]
Thanks Reply
