### ISSUE TITLE
EDRSandblast_API does not restore MiniFilter Callbacks

### ISSUE THREAD

**Issue by rafaelscheel** [wavestone-cdt/EDRSandblast#30]
In EDRSandblast_API -> Krnlmode_RestoreAllMonitoring, EnableEDRProcessAndThreadObjectsCallbacks is called twice instead of RestoreEDRMinifilterCallbacks.
I tested the change and RestoreEDRMinifilterCallbacks seems to work great. 

Will make the pull request.

**Comment by themaks** [comment]
Thanks for the contribution !
