### ISSUE TITLE
Support for ObRegisterCallbacks

### ISSUE THREAD

**Issue by waawaa** [wavestone-cdt/EDRSandblast#9]
It would be interesting to add  support for bypass ObRegisterCallbacks LSASS protection.
Also could be interesting to add other weaponized drivers.

Do you accept collaboration??

**Comment by themaks** [comment]
Hi,
It would be indeed very useful, I’m glad we already implemented that 😄 
It is in the defconrelease branch for the moment ;)
Have fun

ps: if you have other ideas, do not hesitate to communicate them, and yes, we are open for contributions !

**Comment by CM-1207** [comment]
Hi, that sounds good. I accept the collaboration. What can I do?

    2022년 8월 18일 목요일 오후 06시 35분 14초 GMT+9, Alejandro Pinna ***@***.***> 작성:  
 
 


It would be interesting to add support for bypass ObRegisterCallbacks LSASS protection.
Also could be interesting to add other weaponized drivers.

Do you accept collaboration??
